baseURL = "https://alirtech.netlify.app"
languageCode = "id-id"
title = "Alirtech || Sharing dan belajar"
theme = "alirtech"
summaryLength = 10
paginate = 6
[params]
    Description = "Komunitas Belajar dan Sharing"
[taxonomies]
    category = "categories"
    tag = "tags"
    topik = "topik"
    bahasa = "bahasa"
